cv:
	pdflatex MonlongJeanCV.tex
	bibtex MonlongJeanCV.aux
	pdflatex MonlongJeanCV.tex
	pdflatex MonlongJeanCV.tex

clean:
	rm MonlongJeanCV.aux MonlongJeanCV.bbl MonlongJeanCV.blg MonlongJeanCV.log  MonlongJeanCV.pdf
